---
title: "Food/Refreshments"
toc-depth: 2
---

Planning for food involves thoughtful planning to ensure participants are comfortable or excited/interested in the food options. It is important to provide meals/refreshments or snacks, primarily if the focus group or facilitation session is held during a lunch or dinner hour. Even if not during those times, providing a light snack is a courtesy we should try to incorporate to support engagement. Review the following considerations:

## Participant Preferences

- Consider dietary restrictions: Check in with participants about allergies and dietary restrictions (e.g., gluten-free, vegetarian, kosher, etc.).

- Consider local businesses and what the client recommends as community favorites 

- Consider cultural foods: Food choices may be affected by cultural preferences/restrictions 

- Consider age of participants: Tailor food options familiar to the age groups (e.g., youth-friendly snack). 

- Pizza goes over well with families typically, especially with youth. Side salad also goes over well. 

##Food Options

- Non-messy: pick foods/snacks that are easy to eat and not messy (e.g., bite-size portions)

  - Examples: Mini bagels and cream cheese; cubed cheese, crackers, and fruit platter; soft cookies, muffins, sliced banana bread, etc.

- Non-noisy: Avoid crunchy foods or items with wrappers that may affect the sound quality of a recording 

- Health conscious foods: Include healthy options like fresh fruits/vegetables or snacks, considering access to fresh foods may be challenging for some communities and are deserving of a meal/snack that is good for them (this doesn’t mean fun foods like pizza are not encouraged, but including a mix of options si recommended)

  - Healthy foods like a fruit tray is well received (e.g., grapes, cut melon, strawberries, etc.), but it can also be helpful to mix in more "dessert" types of foods (e.g., soft cookies, mini muffins) for variety.

## Beverage Options

- Water: Keep participants hydrated and avoid providing sugary beverages. If you are concerned about the waste of bottled water, you could provide pitchers of cool water with cups.

- Coffee: Consider for morning events and/or from a cultural context that coffee is often consumed during catch-up/conversations. Bring creamer, sugar, and stirrers/spoons.

- Tea: You may also wish to make available herbal and caffeinated tea options. If so, plan to also bring along a kettle if needed or ensure the location has one available 

## Budgeting

- Follow the budgetary amount set aside for refreshments. With that in mind, if you're unsure how much food to buy or serve, it's better to have a little extra rather than not enough. We want to make sure everyone has a chance to enjoy the food. Any leftovers can be offered to participants or staff to take home if they're interested.

## Additional considerations:

- Bring other materials that are needed such as napkins, plates, cups, and serving trays. 

- The facilitator may incorporate breaks for participants to grab a snack, like a restroom break

- Bring cleaning supplies such as Clorox wipes before placing the meals/snacks and after for clean-up

- Label foods (if necessary) for participants to easily choose their preferences

## Previous Project Examples:

- On Kids Count, a dinner of pizza, Santiagos Rice/beans, or Qdoba etc. was typically just under \$200 for a group of 25, including water and King Soopers cookies for dessert. Breakfast sessions were about $150 for food (bagels, fruit, etc.), water, and coffee for 25 people